version: "3.10"

services:
    backend:
        platform: Linux/arm64
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/mspe/backend
        ports:
            - "8000:8000"
        container_name: mspe_backend
        command: >
            sh -c "python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"
        depends_on:
            - db

    db:
        image: postgres
        volumes:
            - ./data/db:/var/lib/postgresql/data
        env_file:
            - ".env"
        ports:
            - "5432:5432"
        container_name: mspe_db

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        volumes:
            - ./frontend:/mspe/frontend
        container_name: mspe_frontend
        depends_on:
            - backend
