version: "3.10"

services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/app
            - static_volume:/app/static
            - media_volume:/app/media
        ports:
            - "8000:8000"
        command: >
            sh -c "python manage.py collectstatic --noinput &&
            python manage.py migrate &&
            gunicorn mspe.wsgi:application --bind 0.0.0.0:8000"
        depends_on:
            - db

    db:
        image: postgres
        volumes:
            - ./data/db:/var/lib/postgresql/data
        env_file:
            - ".env"
        ports:
            - "5432:5432"
        container_name: mspe_db

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        volumes:
            - ./frontend:/var/www/frontend
        restart: on-failure
        depends_on:
            - backend

    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        volumes:
            - static_volume:/app/staticfiles
            - media_volume:/app/mediafiles
        ports:
            - "80:80"
        depends_on:
            - backend
            - frontend

volumes:
    frontend:
    static_volume:
    media_volume:
