version: "3.10"

services:
    db:
        image: postgres
        volumes:
            - ./data/db:/var/lib/postgresql/data
        env_file:
            - ".env"
        ports:
            - "5432:5432"
        container_name: mspe_db
