# Generated by Django 4.0.4 on 2022-06-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('1', 'error'), ('2', 'warning'), ('3', 'info'), ('4', 'success')], default='1', max_length=8)),
            ],
        ),
    ]
