# Generated by Django 4.0.4 on 2022-06-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
