# Generated by Django 3.1.4 on 2021-03-25 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technologies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('more_info', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DevelopmentTech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='development.development')),
                ('tech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='development.technologies')),
            ],
        ),
    ]
