# Generated by Django 3.1.4 on 2021-03-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0004_development_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='development',
            name='logo',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='development_logos'),
        ),
    ]
