# Generated by Django 3.1.4 on 2021-04-22 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0005_auto_20210327_1553'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='development',
            options={'ordering': ('-created_date',)},
        ),
    ]
