# Generated by Django 3.2.4 on 2021-06-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0006_auto_20210422_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='development',
            name='logo',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='development_logos'),
        ),
    ]
