# Generated by Django 3.2.4 on 2021-06-13 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0007_alter_development_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='development',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='development_logos'),
        ),
    ]
